#!/bin/sh
#
#	Set up a directory so it may be used as a souce for FIP
#
path=$1
if [ -z ${path} ] ; then
	echo usage: $0 sourceDirectory
	exit 1
fi

if [ ! -d ${path} ] ; then
	echo Error: Not a directory: ${path}
	exit 1
fi

# Check it's not already a source
cfg=${path}/.fip-source
if [ -e ${cfg} ] ; then
	vi ${cfg}
	exit 0
else
	echo "Could not find ${cfg}"
	echo "Perhaps you need to use the 'newSource' command?"
	exit 1
fi
