#!/bin/sh
#
#	Shell script wrapper for the Fip Server, a Java-based installer used to
#	incrementally install large numbers of files across networks.
#

# Run the server
#JAVA_OPTS="-Xms64m -Xmx256m -XX:MaxPermSize=32m"
export JAVA_OPTS="${JAVA_OPTS} -Djava.security.egd=file:/dev/urandom"
java -jar fipserver-1.0.2-shadow.jar -v 39393
