#!/bin/sh
#
#	Shell script wrapper for Fip, a Java-based installer used to
#	incrementally install large numbers of files across networks.
#
sep=""
cp=""
for l in lib/*.jar ; do
	cp=${cp}${sep}${l}
	sep=":"
done
JAVA_OPTS="-Xms64m -Xmx256m -XX:MaxPermSize=32m"
exec java $JAVA_OPTS -classpath ${cp} tooltwist.fip.jetty.FipJettyServer $*

