#!/bin/bash
#
#	Set up a directory so it may be used as a souce for FIP
#
path=$1
if [ -z ${path} ] ; then
	echo usage: $0 destinationDirectory
	exit 1
fi

if [ ! -d ${path} ] ; then
	echo Error: Not a directory: ${path}
	exit 1
fi

# Check it's not already a destination
cfg=${path}/.fip-destination
rm ${cfg}
if [ -e ${cfg} ] ; then
	echo ${cfg} already exists
	echo Error: ${path} is already a FIP destination.
	exit 1
fi

# Ask for the passphrase
sourceUuid=""
while [ -z ${sourceUuid} ] ; do
	echo -n "Source UUID? "
	read sourceUuid
done

# Ask for the passphrase
passphrase=""
while [ -z "${passphrase}" ] ; do
	echo -n "Passphrase? "
	read passphrase
done

# Get a new UUID
uuid=`uuidgen`

# Create the file
echo Creating ${cfg}...
echo "# Configuration to make this directory a destination for FIP (File Installation Protocol)" >> ${cfg}
echo "sourceUuid=${sourceUuid}" >> ${cfg}
echo "destinationUuid=${uuid}" >> ${cfg}
echo "passphrase=${passphrase}" >> ${cfg}

# Display a nice message
echo ""
echo "Please note:"
echo "The following line will need to be added to the source definition file:"
echo ""
echo "    ${uuid}=${passphrase}"
echo ""
exit 0
