#!/bin/sh
#
#	Set up a directory so it may be used as a souce for FIP
#
path=$1
if [ -z ${path} ] ; then
	echo usage: $0 sourceDirectory
	exit 1
fi

if [ ! -d ${path} ] ; then
	echo Error: Not a directory: ${path}
	exit 1
fi

# Check it's not already a source
cfg=${path}/.fip-source
if [ -e ${cfg} ] ; then
	echo ${cfg} already exists
	echo ""
	echo Error: ${path} is already a FIP source.
	exit 1
fi

# Get a new UUID
uuid=`uuidgen`

# Create the config file
echo Creating ${cfg}...
echo "# Configuration to make this directory a source for FIP (File Installation Protocol)" >> ${cfg}
echo "sourceUuid=${uuid}" >> ${cfg}

# Display a useful message
echo "Please note the following UUID for this source, which will be used"
echo "when you create destinations using the newDestination' command:"
echo ""
echo "    Source UUID: ${uuid}"
echo ""
exit 0
