#!/bin/sh
#
#	This command can be run once after unzipping the fip commands. It will
#	remove the OSX quarantine extended attribute from all files.
#
echo ""
echo Before:
ls -l@
xattr -dr com.apple.quarantine .
chmod +x start_fipserver.sh newFipSourceAndDestination

echo ""
echo After:
ls -l@
exit 0;
